# Generated by Django 4.1.7 on 2023-03-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='id',
        ),
        migrations.AlterField(
            model_name='grade',
            name='classes',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
