# Generated by Django 4.1.7 on 2023-03-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
