# Generated by Django 4.1.7 on 2023-03-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_grade_id_alter_grade_classes'),
        ('user', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='admins.grade'),
        ),
    ]
